package com.maplenou.backend.audit;

public enum AuditAction {
    USER_ANONYMIZED,
    USER_ROLE_CHANGED,
    USER_BANNED,
    USER_UNBANNED,
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    SHOP_STATUS_CHANGED,
    RETURN_DECIDED,
    PROMO_CODE_CREATED,
    PROMO_CODE_STATUS_CHANGED,
    SUBORDER_STATUS_CHANGED_ADMIN,
    TWO_FA_ENABLED,
    TWO_FA_DISABLED,
    SELLER_APPROVED,
    SELLER_REJECTED,
    PAYOUT_GENERATED,
    PAYOUT_PROCESSING,
    PAYOUT_MARKED_PAID,
    PAYOUT_MARKED_FAILED,
    CONTENT_PAGE_CREATED,
    CONTENT_PAGE_UPDATED,
    CONTENT_PAGE_DELETED
}
